AppConfig:
  ExtensionFilter: "*.log"
  RegexMasks:
    - Pattern: "^password\\s*(=|:)\\s*\\S+$"
      Replacement: "password$1 ***PASSWORD***"
    - Pattern: "^[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}$"
      Replacement: "***LICENCE KEY***"
  BannedWords:
    - Word: "master"
      Replacement: "primary"
    - Word: "slave"
      Replacement: "secondary"
    - Word: "whitelist"
      Replacement: "allowlist"
    - Word: "blacklist"
      Replacement: "denylist"
    - Word: "manhours"
      Replacement: "personhours"
    - Word: "grandfathered"
      Replacement: "legacy"
    - Word: "dummy"
      Replacement: "stub"
    - Word: "sanitycheck"
      Replacement: "integritycheck"
    - Word: "masterpassword"
      Replacement: "mainpassword"
